Secrets - typos fixes, review enhancments

diff --git a/secret/bash-export b/secret/bash-export
--- a/secret/bash-export
+++ b/secret/bash-export
@@ -2,9 +2,12 @@
 
 source $(dirname $(realpath "$0"))/.shared
 
-: ${1?"$(usage "Not enough arguments: `basename $0` <var1> [var2, var3...]")"}
-readonly VAR="${1}"
+: ${1?"$(usage "Not enough arguments: $(basename $0) <var1> [var2, var3...]")"}
 
 for _var in "$@"; do
-    echo "export ${_var}=\"$($(dirname $(realpath "$0"))/get ${_var})\""
+    _val="$($(dirname $(realpath "$0"))/get ${_var})" || {
+        echo "Failed to get secret: ${_var}" >&2
+        exit 1
+    }
+    echo "export ${_var}=\"${_val}\""
 done
